### ISSUE TITLE
[Question] Stepper pins numbers

### ISSUE THREAD

**Issue by jorgerobles** [teofr/Slider#1]
Hi!

Maybe a dumb question. What pins are 30 and 31 ? I cannot find those pins on Arduino UNO.. 
Is this sketch for Leonardo?
Thanks!

**Comment by teofr** [comment]
Hi, I'm sorry for the late answer.
It's a sketch for Arduino Mega, which does have many more pins.
I guess you can change the pins and it should work.

Are you doing a similar project?

**Comment by jorgerobles** [comment]
Hi @teofr ok, I'm using UNO, so moved the pins to ones available.
I'm also figuring out microstepping, as using a A4988 fullstep was making a horrible noise :)

**Comment by teofr** [comment]
That's a good idea, I don't remember why I didn't go for micro stepping.
